ContentsTree = new CTree("ContentsTree");
ContentsTree.bAutoClose = true;
ContentsTree.stTarget = "Main";
f1 = ContentsTree.AddNode(null, "统计分析总揽", "General_Statistics.htm");
ContentsTree.AddNode(f1, "统计分析概要", "General_Statistics.htm#Summary");
f2 = ContentsTree.AddNode(null, "当前统计分析报表", "Activity_Statistics.htm");
ContentsTree.AddNode(f2, "每日", "Activity_Statistics.htm#Daily");
ContentsTree.AddNode(f2, "小时/日", "Activity_Statistics.htm#By_Hour_of_Day");
ContentsTree.AddNode(f2, "日/周", "Activity_Statistics.htm#By_Day_of_Week");
ContentsTree.AddNode(f2, "月份", "Activity_Statistics.htm#By_Month");
f3 = ContentsTree.AddNode(null, "页面访问统计", "Access_Statistics.htm");
ContentsTree.AddNode(f3, "页", "Access_Statistics.htm#Pages");
ContentsTree.AddNode(f3, "文件", "Access_Statistics.htm#Files");
ContentsTree.AddNode(f3, "图片", "Access_Statistics.htm#Images");
ContentsTree.AddNode(f3, "目录", "Access_Statistics.htm#Directories");
ContentsTree.AddNode(f3, "进入页面", "Access_Statistics.htm#Entry_Pages");
ContentsTree.AddNode(f3, "离开页面", "Access_Statistics.htm#Exit_Pages");
ContentsTree.AddNode(f3, "路径", "Access_Statistics.htm#Paths");
ContentsTree.AddNode(f3, "文件类型", "Access_Statistics.htm#File_Types");
f4 = ContentsTree.AddNode(null, "访客", "Visitors.htm");
ContentsTree.AddNode(f4, "主机", "Visitors.htm#Hosts");
ContentsTree.AddNode(f4, "顶级域名", "Visitors.htm#Top_Level_Domains");
ContentsTree.AddNode(f4, "国家", "Visitors.htm#Countries");
f5 = ContentsTree.AddNode(null, "引用来源", "Referrers.htm");
ContentsTree.AddNode(f5, "引用站点", "Referrers.htm#Referring_Sites");
ContentsTree.AddNode(f5, "引用地址", "Referrers.htm#Referring_URLs");
f6 = ContentsTree.AddNode(null, "浏览器", "Browsers.htm");
ContentsTree.AddNode(f6, "浏览器", "Browsers.htm#Browsers");
ContentsTree.AddNode(f6, "操作系统", "Browsers.htm#Operating_Systems");
ContentsTree.AddNode(f6, "搜索引擎抓取机器人", "Browsers.htm#Spiders");
f7 = ContentsTree.AddNode(null, "错误信息", "Errors.htm");
ContentsTree.AddNode(f7, "类型", "Errors.htm#Types");
ContentsTree.AddNode(f7, "404错误", "Errors.htm#404_Errors");
ContentsTree.AddNode(f7, "其他错误", "Errors.htm#Other_Errors");
document.write(ContentsTree.GetHTMLCode());